<?php
function nvweb_sitemap($vars=array())
{
	global $website;
	global $DB;
	global $current;
	global $cache;
	global $structure;

	$out = array();

    switch($vars['mode'])
    {
        case 'xml':
            header('Content-Type: text/xml');

            $out[] = '<?xml version="1.0" encoding="UTF-8"?>';
            $out[] = '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';

            // HOMEPAGE

            $out[] = '  <url>';
            $out[] = '      <loc>'.nvweb_sitemap_escape_xml(NVWEB_ABSOLUTE.$website->homepage()).'</loc>';
            $out[] = '      <lastmod>'.date(DATE_W3C, time()).'</lastmod>';
            $out[] = '      <changefreq>daily</changefreq>';
            $out[] = '      <priority>1</priority>';
            $out[] = '  </url>';

            // STRUCTURE paths

            $DB->query('
                SELECT p.object_id, p.lang, p.path, s.position
				FROM nv_paths p, nv_structure s
				WHERE p.type = "structure"
				  AND p.website = '.$website->id.'
				  AND s.website = '.$website->id.'
				  AND s.id = p.object_id
				  AND s.permission = 0
                  AND (s.date_published = 0 OR s.date_published < '.core_time().')
                  AND (s.date_unpublish = 0 OR s.date_unpublish > '.core_time().')
				ORDER BY s.position ASC
            ');

            $data = $DB->result();
            $structure_paths = array();
            if(is_array($data))
            {
                foreach($data as $item)
                {
                    $structure_paths[$item->position.'-'.$item->object_id.'-'.$item->lang] = $item->path;
                }
            }

            foreach($structure_paths as $key => $value)
            {
                if(strpos($value, 'http')===false)
                {
                    $value = NVWEB_ABSOLUTE.$value;
                }

                $out[] = '  <url>';
                $out[] = '      <loc>'.nvweb_sitemap_escape_xml($value).'</loc>';
                $out[] = '      <lastmod>'.date(DATE_W3C, time()).'</lastmod>';
                $out[] = '      <changefreq>weekly</changefreq>';
                $out[] = '      <priority>0.75</priority>';
                $out[] = '  </url>';
            }

            // ITEM paths

            $DB->query('
                SELECT p.object_id, p.lang, p.path, i.date_modified
				FROM nv_paths p, nv_items i
				WHERE p.type = "item"
				  AND p.website = '.$website->id.'
				  AND i.website = '.$website->id.'
				  AND i.id = p.object_id
				  AND i.permission = 0
				  AND (i.association = "free" OR (i.association = "category" AND i.embedding=0))
                  AND (i.date_published = 0 OR i.date_published < '.core_time().')
                  AND (i.date_unpublish = 0 OR i.date_unpublish > '.core_time().')
				ORDER BY i.position ASC
            ');

            $data = $DB->result();
            $item_paths = array();
            if(is_array($data))
            {
                foreach($data as $item)
                {
                    $item_paths[$item->position.'-'.$item->object_id.'-'.$item->lang] = array($item->path, $item->date_modified);
                }
            }

            foreach($item_paths as $key => $value)
            {
                $out[] = '  <url>';
                $out[] = '      <loc>'.nvweb_sitemap_escape_xml(NVWEB_ABSOLUTE.$value[0]).'</loc>';
                $out[] = '      <lastmod>'.date(DATE_W3C, $value[1]).'</lastmod>';
                $out[] = '      <changefreq>monthly</changefreq>';
                $out[] = '      <priority>0.5</priority>';
                $out[] = '  </url>';
            }

            // TODO: call an extension event to add more paths generated by plugins (answers, etc.)

            $out[] = '</urlset>';
            break;
    }

	return implode("\n", $out);
}

function nvweb_sitemap_escape_xml($url)
{
    $url = str_replace(
        array('<', '>', '&', '"', "'"),
        array('&lt;', '&gt;', '&amp;', '&quot;', "&apos;"),
        $url
    );

    return $url;
}

?>