0 		# Navigate
1 		# Usuari
2 		# Contrassenya
3		# Accedir
4		# Dades d'identificació incorrectes.
5		# Tancar sessió
6		# Carregant
7		# Configuració
8		# Web
9		# Contingut
10		# Botiga
11		# Multimedia
12		# Eines
13		# phpMyAdmin
14		# Preferències
15		# Usuaris
16		# Estructura
17		# Permisos
18		# Inici
19		# Estructura
20		# Plantilles
21		# Diccionari
22		# Elements
23		# Blocs
24		# Usuaris web
25		# Productes
26		# Comandes
27		# Tarifes
28		# Ports
29		# Imatges
30		# Vídeos
31		# Audio
32		# Documents
33		# Butlletins
34		# Guardar
35		# Esborrar
36		# Media
37		# NaviM+
38		# Crear
39		# Llistar
40		# Historial
41		# Cercar
42		# Preparat
43		# Principal
44		# E-Mail
45		# Perfil
46		# Idioma
47		# Bloquejat
48		# Deixar buit per mantenir el valor actual
49		# Separador decimal
50		# Format de data
51		# Llista
52		# (nou)
53		# Dades guardades correctament
54		# Text
55		# Element esborrat correctament
56		# Error inesperat
57		# Realment vol esborrar l'element?
58		# Cancel·lar
59		# Confirmació
60		# Realmente vol esborrar els elements escollits?
61		# Arbre
62		# Estadístiques
63		# Idiomes
64		# Publicat
65		# Activat
66		# Prioritat
67		# Títol
68		# Estat
69		# Publicada
70		# Privada
71		# Tancada
72		# Arrossegui les files per determinar la prioritat
73		# Fills
74		# Rutes
75		# Ruta
76		# Visible
77		# Propietats
78		# Categoria
79		# Plantilla
80		# Permís
81		# Amagada
82		# Fitxer
83		# Deixar en blanc per a inhabilitar
84		# Pare
85		# Data de publicació
86		# Data
87		# Associació
88		# Galeries
89		# Fitxers
90		# Data de despublicació
91		# Dia del mes
92		# Tancar
93		# Hora
94		# Minut
95		# Mes
96		# Segon
97		# Zona horària
98		# Esculli una data
99		# Any
100		# Lliure
101		# Gener
102		# Febrer
103		# Març
104		# Abril
105		# Maig
106		# Juny
107		# Juliol
108		# Agost
109		# Setembre
110		# Octubre
111		# Novembre
112		# Desembre
113		# Gen
114		# Feb
115		# Mar
116		# Abr
117		# Mai
118		# Jun
119		# Jul
120		# Ago
121		# Set
122		# Oct
123		# Nov
124		# Des
125		# Dilluns
126		# Dimarts
127		# Dimecres
128		# Dijous
129		# Divendres
130		# Dissabte
131		# Diumenge
132		# Dl.
133		# Dt.
134		# Dm.
135		# Dj.
136		# Dv.
137		# Ds.
138		# Dg.
139		# Enrera
140		# Carregar
141		# Carpeta
142		# Escollir fitxers
143		# Afegeixi fitxers a la cua de pujada i premi el botó per a iniciar la càrrega
144		# Nom del fitxer
145		# Tamany
146		# Escollir fitxers
147		# Iniciar càrrega
148		# Aturar càrrega actual
149		# Iniciar cua de càrrega
150		# Arrossegui fitxers aquí
151		# Els elements escollits seran esborrats i no podran ser recuperats.
152		# Continuar
153		# Enllaç d'integració
154		# Enllaç de descàrrega
155		# Ample
156		# Alt
157		# Imatge
158		# Miniatura
159		# Nom
160		# Tipus
161		# Genèric
162		# Incrustació
163		# Incrustat
164		# Ruta pròpia
165		# El contingut complet es mostra a la vista de categoria. Ex. "Qui som?"
166		# S'accedeix al contingut a través d'una ruta independent. Ex. "Notícies"
167		# Tipus
168		# Notes
169		# Pot deixar en blanc un camp per a no limitar la mida
170		# Editar
171		# Ordenar
172		# Acció
173		# Seguir URL
174		# Obrir URL (nova finestra)
175		# Descarregar fitxer
176		# Veure imatge
177		# Lloc web
178		# Serveis
179		# Miniatures
180		# Element
181		# Ocult
182		# Imatge activa
183		# No fer res
184		# Pàgina web
185		# Cercant elements
186		# Adobe Flash
187		# Pàgina inicial
188		# Traduir
189		# Copiar de
190		# Acceptar
191		# Origen
192		# Faci doble clic sobre una fila per a editar-la
193		# Valor
194		# Opció
195		# Àrea de text
196		# Data y hora
197		# Enllaç
198		# Artícle
199		# Valor per defecte
200		# Opcions
201		# Una línia per cada opció, seguint el format: valor#títol
202		# Escrigui només el valor
203		# El mateix valor per a tots els idiomes
204		# ID del fitxer
205		# Comentari
206		# Booleà
207		# Zona horària per defecte
208		# Data actual aplicant l'ajust
209		# Minuts
210		# Galeria
211		# Opció múltiple
212		# Escrigui els valors escollits separant-los amb comes
213		# Text de la imatge
214		# Producte
215		# Crèdits
216		# Creat per
217		# Provat per
218		# Llibreries externes
219		# Copyright
220		# Versió
221		# Saltar a
222		# Valoració
223		# Per defecte 5 estrelles, si vol un número diferent: valor_defecte#número_estrelles
224		# País
225		# Codi alpha-2 del país
226		# Data de creació
227		# Data de modificació
228		# Subdomini
229		# Domini
230		# Ex.
231		# Servidor
232		# Port
233		# Adreça
234		# Més elements
235		# Fitxer guardat correctament.
236		# Seccions
237		# Codi
238		# Contingut principal
239		# Secció
240		# Funcions
241		# Llocs web
242		# Icona
243		# Perfils
244		# Menús
245		# Notes
246		# Avatar
247		# Data de registre
248		# Data de naixement
249		# Butlletí electrònic
250		# Comentaris
251		# Privat
252		# Comentaris actius per a
253		# Ningú
254		# Tothom
255		# Moderador
256		# Deixar en blanc per a acceptar tots els comentaris
257		# Per revisar
258		# Publicar
259		# Despublicar
260		# Arrossegui i deixi anar fitxers per a carregar-los
261		# Carregant
262		# Error carregant fitxer
263		# Correus electrònics de contacte
264		# Una entrada per línia
265		# Etiquetes
266		# Autor/a
267		# Editor
268		# Sense format
269		# Codi HTML
270		# Guardant automàticament
271		# Guardat automàtic completat
272		# Vídeo
273		# Autoguardat
274		# Previsualitzar
275		# Elements recents
276		# Comentaris recents
277		# Elements més vistos
278		# Resum de la web
279		# Pàgines disponibles
280		# Pàgines vistes
281		# Comentaris per revisar
282		# Sense títol
283		# Es mostra als menús
284		# Àfrica
285		# Actualitzar
286		# Arrossegui per a reordenar. Faci doble clic per a assignar títols a la imatge.
287		# Protocol
288		# Lloc segur (requereix certificat)
289		# Actualitzar Navigate
290		# Versió actual
291		# Última versió
292		# Actualitzacions disponibles
293		# Actualitzat correctament.
294		# Error actualitzant.
295		# Expandir tot
296		# Pàgines més vistes
297		# Coordenades
298		# Latitut
299		# Longitut
300		# Mapa
301		# Faci doble clic en un indret per establir les coordenades
302		# Ajuda
303		# Actualització manual
304		# Sexe
305		# Masculí
306		# Femení
307		# No especificat
308		# Personal
309		# Social
310		# Amèrica
311		# Antàrtida
312		# Àrtic
313		# Àsia
314		# Atlàntic
315		# Europa
316		# Índic
317		# Pacífic
318		# Codi postal
319		# Localitat
320		# Telèfon
321		# Permès
322		# Saltar a una altra branca
323		# Saltar a un element
324		# Nova finestra
325		# Branca
326		# Fonts web
327		# Extensions
328		# Favicon
329		# Còpies de seguretat
330		# Categories
331		# Format
332		# Vistes
333		# Recomanat
334		# Descripció
335		# Entrades
336		# Mostrar
337		# Resum
338		# Carregats %d/%d fitxers
339		# No disponible
340		# Error en la extensió del fitxer
341		# Error en la mida del fitxer
342		# Error d'inicialització
343		# Error HTTP
344		# Error de segurertat
345		# Error genèric
346		# Error d'entrada/sortida
347		# Aturar càrrega
348		# Afegir fitxers
349		# Iniciar càrrega
350		# %d fitxers a la cua
351		# Nova actualització disponible!
352		# Vots
353		# Nota
354		# Reiniciar
355		# Vots reiniciats
356		# últims 90 dies
357		# Vots dels usuaris
358		# No es mostra a ningú
359		# Només visible per a usuaris de Navigate CMS
360		# Es mostra a tothom
361		# Només usuaris registrats
362		# No registrats
363		# Usuaris que encara no s'han registrat o identificat
364		# Accés
365		# Instal·lar
366		# Registre
367		# Temes
368		# Tema
369		# Més a
370		# Demo
371		# Instal·lar un nou tema reemplaça la configuració de l'anterior.
372		# La llista de tipus de blocs disponibles es pot perdre així com les propietats assignades a elements.
373		# Realment vol continuar?
374		# Element instal·lat correctament.
375		# Blog
376		# Entrada de blog
377		# Contacte
378		# Llicència
379		# Escriure un comentari
380		# Missatge
381		# El correu electrònic no serà mostrat
382		# Enviar
383		# Identifiqueu o Registreu-vos per a escriure un comentari
384		# Els comentaris per a aquesta entrada estan tancats
385		# Si us plau, no deixi cap camp en blanc
386		# El seu comentari ha estat rebut i serà publicat pròximament
387		# Nou comentari
388		# Revisar comentaris
389		# Protecció de tecla Retrocés
390		# Provar
391		# Intentant enviar un correu de prova...
392		# Missatge enviat
393		# Tamanys publicitaris estàndard
394     # Fix
395     # "Fix" determina una posició estàtica quan l'ordre és aleatori
396		# Totes les categories
397		# Màxim
398		# Mínim
399		# Aleatori
400		# Escrigui 0 per a mostrar-los tots
401		# El seu navegador no integra HTML5
402		# Si us plau, esculli un número més petit de fitxers
403		# Fitxer massa gran
404     # Ordenar per
405     # Selecció
406     # Recordar-me
407     # Ha oblidat la contrassenya?
408     # L'ordre només s'utilitza en llistes ordenades per prioritat
409     # Mida
410     # Iniciar còpia de seguretat
411     # Progrés de la tasca
412     # Restaurar
413     # Esperant per a començar
414     # Exportant base de dades
415     # Copiant temes i plantilles
416     # Copiant extensions
417     # Copiant fitxers carregats
418     # Creant fitxer comprimit
419     # Procés completat
420     # Mida estimada
421		# Data de creació
422     # Transferint al servidor
423     # Comprovar
424     # Preparant procés
425     # Ordenar els elementos d'una categoría (excepte quan la plantilla força una altra ordenació)
426     # Introdueixi "1" per cert, "0" per fals
427     # TLS/SSL requerit
428     # (sense categoria)
429     # Reiniciar estadístiques
430     # Realment vol esborrar totes les estadístiques d'aquest lloc web?
431     # Estil
432     # Mode de només lectura
433		# Mida imatges carregades
434		# Conservar fitxer original
435		# Ample o alt màxim
436     # Usat com una classe en elements HTML
437     # Bloc
438     # Ordenació
439     # Error carregant el tema
440     # Error guardant les dades, si us plau faci una còpia externa dels canvis que ha realitzat per a evitar pèrdues de dades
441     # Color
442     # Codi de color hexadecimal
443     # Tots
444     # Ha deixat alguns camps requerits en blanc.
445     # La seva sol·licitud de contacte ha estat enviada. Aviat ens posarem en contacte amb vosté.
446     # Ho sentim. La seva sol·licitud de contacte no ha pogut ser entregada. Si us plau, torni-ho a intentar o esculli una altra via per a contactar amb nosaltres.
447     # Col·lecció
448     # Element de col·lecció
449     # Introdueixi el seu nom d'usuari de Navigate CMS o la seva adreça de correu electrònic
450     # Faci clic en l'enllaç inferior per a canviar la seva contrassenya
451     # Aquest és un correu automàtic enviat com a resultat d'un procés de petició de canvi de contrassenya. Si ha rebut aquest correu per error simplement ignori'l.
452     # No s'ha pogut enviar el correu electrònic; si us plau contacti amb l'administrador
453     # No s'ha trobat aquest nom d'usuari o adreça de correu
454     # S'ha enviat un correu electrònic a la seva adreça amb un enllaç de confirmació.
455     # La seva nova contrassenya ha estat actividad.
456     # Editar a Navigate CMS
457     # Informació
458     # Editar a la página
459     # Ajustos
460     # Desactivar
461     # Instal·lar des d'un fitxer
462     # Activar
463     # Actualització disponible
464     # Preferit
465     # Preferits
466     # No desitjat (Spam)
467     # Àmbit
468     # Enter
469     # Cadena
470     # Sistema
471     # Variant
472     # Afegir
473     # Regió
474     # Locale al servidor
475     # Exportar
476     # Copiar al portapapers
477     # Duplicar
478     # Element duplicat correctament.
479     # Entrada a estructura
480     # Exportar contingut d'exemple
481     # Seleccionar tot
482     # Tots els fitxers d'exemple hauran d'estar a una carpeta. Navigate CMS afegirà tots els fitxers utilitzats als continguts.
483     # Realment vol importar el lloc web per defecte del tema escollit?
484     # Web demo
485     # Alternatives
486     # Àlies
487     # Adreça real
488     # Àrea de text amb estils
489     # Codi fuente
490     # ID del fitxer o URL pública del vídeo
491     # Classe
492     # No s'han trobat resultats
493     # Carregant més dades...
494     # Cercant...
495     # Si us plau, introduexi un mínim de {number} caràcters
496     # Només pot escollir {number} elements
497     # Realment vol eliminar les dades?
498     # Scripts addicionals
499     # Obrir
500     # Canviar nom
501     # Anterior
502     # Següent
503     # Ara
504     # Hora
505     # Redirigir a
506     # Grups
507     # Deseleccionar tot
508     # Plegar
509     # Desplegar
510     # Elements seleccionats
511     # Elements disponibles
512     # Selecció de grups d'usuaris web
513     # Metatags
514     # Capçaleres adicionals
515     # Les rutes no trobades
516     # Mostren una pàgina en blanc
517     # Redirigeixen a la pàgina d'inici
518     # Fan servir la plantilla 404 d'un tema (si existeix)
519     # Envien una capçalera d'error HTTP 404
520     # Cap lloc web trobat; se n'ha creat un per defecte.
521     # Extra
522     # Esborrar Spam
523     # Aquesta operació no podrà desfer-se.
524     # Elements esborrats correctament
525     # Esborrar comentari (sense confirmació)
526     # Traduccions
527     # Mercat
528     # Disponibles
529     # No ha estat possible descarregar l'objecte des de la botiga.
530     # Haurà de visitar la seva zona privada a la botiga per a descarregar el fitxer, llavors fer servir el botó <strong>Instal·lar des de fitxer</strong> que trobarà a la barra d'accions de la dreta.
531     # Disculpi les molèsties.
532     # Botiga de Navigate CMS
533     # Trobar un element per títol
534     # Només pot escollir elements que tinguin ruta pròpia (no elements incrustats a una categoria)
535     # Trobar un usuari per nom
536     # Paraules clau
537     # No es pot esborrar el tema perquè actualment està essent utilitzat per un altre lloc web.
538     # Comentari privat
539     # Document
540     # Punt focal
541     # El seu correu electrònic ha estat correctament subscrit al butlletí.
542     # Hi ha hagut un problema subscribint el seu correu electrònic al butlletí.
543     # Tipus de bloc
544     # Grups de blocs
545     # Autor del contingut
546     # Accions
547     # Multi-idioma
548     # Mètode
549     # Enllaços
550     # Text d'ajuda
551     # Data a mostrar
552     # Exclusions
553     # Fragments
554     # Amagar
555     # L'element ha estat publicat correctament.
556     # Bloc del grup
557     # Enquesta
558     # Pregunta
559     # Respostes
560     # Votar
561     # Crear nova carpeta
562     # Resultats
563     # Última visita
564     # fa %s segons
565     # fa un minut
566     # fa %m minuts
567     # fa una hora
568     # fa %h hores
569     # ahir
570     # fa %d dies
571     # fa una setmana
572     # fa %w setmanes
573     # fa un mes
574     # fa %m mesos
575     # fa un any
576     # fa %y anys
577     # Últimes modificacions
578     # No s'ha pogut connectar per a comprovar les actualitzacions
579     # Últimes cerques
580     # S'utilitza en aquesta pàgina
581     # Cap