0 		# Navigate
1 		# Benutzer
2 		# Passwort
3		# Enter
4		# Login-Daten nicht korrekt.
5		# Log out
6		# Lädt
7		# Konfiguration
8		# Web
9		# Inhalt
10		# Shop
11		# Multimedia
12		# Werkzeuge
13		# phpMyAdmin
14		# Einstellungen
15		# Benutzer
16		# Struktur
17		# Rechte
18		# Home
19		# Struktur
20		# Templates
21		# Wörterbuch
22		# Elemente
23		# Blöcke
24		# Registrierte Benutzer
25		# Produkte
26		# Bestellungen
27		# Tarife
28		# Versand
29		# Bilder
30		# Videos
31		# Audio
32		# Dokumente
33		# Newsletter
34		# Speichern
35		# Löschen
36		# Medien
37		# NaviM+
38		# Neu
39		# Liste
40		# Verlauf
41		# Suche
42		# Bereit
43		# Allgemein
44		# E-Mail
45		# Profil
46		# Sprache
47		# Blockiert
48		# Leer lassen um den aktuellen Wert zu übernehmen
49		# Dezimalseparator
50		# Datumsformat
51		# Liste
52		# (neu)
53		# Daten erfolgreich gespeichert
54		# Text
55		# Element erfolgreich gelöscht
56		# Unerwarteter Fehler
57		# Möchtest du dieses Element wirklich löschen?
58		# Abbrechen
59		# Bestätigung
60		# Möchtest du die ausgewählten Elemente wirklich löschen?
61		# Baum
62		# Statistiken
63		# Sprachen
64		# Veröffentlicht
65		# Aktiviert
66		# Priorität			
67		# Titel
68		# Status
69		# Veröffentlicht
70		# Privat
71		# Geschlossen
72		# Verschiebe die Reihen um Prioritäten zuzuweisen
73		# Unterkategorie
74		# Pfade
75		# Pfad
76		# Sichtbar
77		# Eigenschaften
78		# Kategorie
79		# Template
80		# Rechte
81		# Versteckt
82		# Datei
83		# Zum Deaktivieren frei lassen
84		# Übergeordnete Kategorie
85		# Veröffentlichungsdatum
86		# Datum
87		# Verknüpfung
88		# Galerien
89		# Dateien
90		# Unveröffentlicht seit
91		# Tag des Monats
92		# Schließen
93		# Stunde
94		# Minute
95		# Monat
96		# Sekunde
97		# Zeitzone
98		# Wähle ein Datum
99		# Jahr
100		# Frei
101		# Januar
102		# Februar
103		# März
104		# April
105		# Mai
106		# Juni
107		# Juli
108		# August
109		# September
110		# Oktober
111		# November
112		# Dezember
113		# Jan
114		# Feb
115		# Mär
116		# Apr
117		# Mai
118		# Jun
119		# Jul
120		# Aug
121		# Sep
122		# Okt
123		# Nov
124		# Dez
125		# Montag
126		# Dienstag
127		# Mittwoch
128		# Donnerstag
129		# Freitag
130		# Samstag
131		# Sonntag
132		# Mo
133		# Di
134		# Mi
135		# Do
136		# Fr
137		# Sa
138		# So
139		# Zurück
140		# Hochladen
141		# Ordner
142		# Dateien wählen
143		# Füge Dateien zur Warteschlange hinzu und klicke auf den Button um den Upload zu starten
144		# Dateiname
145		# Größe
146		# Dateien wählen
147		# Upload starten
148		# Aktuellen Upload abbrechen
149		# Upload-Warteschlange starten
150		# Ziehe Dateien per Drag 'n' Drop hierher
151		# Das gewählte Element wird dauerhaft gelöscht
152		# Weiter
153		# Link zum Einbetten
154		# Download-Link
155		# Breite
156		# Höhe
157		# Bild
158		# Thumbnail
159		# Name
160		# Typ
161		# Allgemein
162		# Einbettung
163		# Eingebettet
164		# Eigener Pfad
165		# Der gesamte Inhalt wird in der Kategorienansicht angezeigt. Bsp. "Wer wir sind" 
166		# Der Inhalt ist über einen eigenen Pfad erreichbar. Bsp. "Neuigkeiten"
167		# Typen
168		# Notizen
169		# Du kannst ein Feld frei lassen um die Größe flexibel zu lassen
170		# Bearbeiten
171		# Sortieren
172		# Aktion
173		# Der URL folgen
174		# URL öffnen (in neuem Fenster)
175		# Datei herunterladen
176		# Bild ansehen
177		# Website
178		# Andere Dienste
179		# Thumbnails
180		# Element
181		# Versteckt
182		# Rollover-Bild
183		# Nichts tun
184		# Webseite
185		# Elemente suchen
186		# Adobe Flash
187		# Homepage
188		# Übersetzen
189		# Kopieren von
190		# Ok
191		# Quelle
192		# Doppelklicke auf eine Reihe um sie zu bearbeiten
193		# Wert
194		# Option
195		# Textfeld
196		# Datum und Uhrzeit
197		# Link
198		# Produkt
199		# Vorgegebener Wert
200		# Optionen
201		# Eine Zeile pro Option in diesem Format: Wert#Bezeichnung
202		# Gib nur den Wert ein
203		# Der gleiche Wert für alle Sprachen
204		# Datei-ID
205		# Kommentar
206		# Boolean
207		# Vorgegebene Zeitzone
208		# Datum mit der aktuellen Einstellung 
209		# Minuten
210		# Galerie
211		# Mehrfachauswahl
212		# Gib die Werte durch Kommas getrennt ein
213		# Bildunterschrift
214		# Produkt
215		# Credits
216		# Erstellt von
217		# Getestet von
218		# Externe Bibliotheken
219		# Copyright
220		# Version
221		# Springe zu
222		# Bewertung
223		# Vorgegebener Wert 5 Sterne, wenn du einen anderen Wert willst: vorgegebener_wert#anzahl_der_sterne
224		# Land
225		# Alpha-2 Ländercode
226		# Erstellungsdatum
227		# Modifikationsdatum
228		# Subdomain
229		# Domain
230		# Bsp.
231		# Server
232		# Port
233		# Adresse
234		# Mehr Elemente
235		# Datei erfolgreich gespeichert.
236		# Sektionen
237		# Code
238		# Hauptinhalt
239		# Sektion
240		# Funktionen
241		# Websites
242		# Icon
243		# Profile
244		# Menüs
245		# Notizen
246		# Avatar
247		# Registrierungsdatum
248		# Geburtsdatum
249		# Newsletter
250		# Kommentare
251		# Privat
252		# Kommentare aktiviert für
253		# Niemanden
254		# Jeden
255		# Moderator
256		# Leer lassen um alle Kommentare zuzulassen
257		# Zu überarbeiten
258		# Veröffentlichen
259		# Veröffentlichung rückgängig machen
260		# Ziehe Dateien per Drag 'n' Drop um sie hochzuladen
261		# Lädt hoch
262		# Fehler beim Hochladen der Datei
263		# Kontakt-E-Mails
264		# Ein Eintrag pro Zeile	
265		# Label
266		# Autor
267		# Editor
268		# Unformatiert
269		# HTML-Code
270		# Autospeichern läuft
271		# Autospeichern abgeschlossen
272		# Video
273		# Autospeichern
274		# Vorschau
275		# Kürzlich bearbeitet
276		# Neuste Kommentare
277		# Meist betrachtet
278		# Web-Übersicht
279		# Verfügbare Seiten
280		# Pageviews
281		# Kommentare zur Überarbeitung
282		# Ohne Titel
283		# In Menüs anzeigen
284		# Afrika
285		# Update
286		# Verschieben um die Reihenfolge zu ändern. Doppelklicken um die Bildunterschrift einzugeben
287		# Protokoll
288		# Sichere Seite (benötigt ein Zertifikat)
289		# Navigate updaten
290		# Aktuelle Version
291		# Letzte Version
292		# Verfügbare Updates
293		# Die Anwendung wurde erfolgreich aktualisiert
294		# Fehler beim Aktualisieren
295		# Alle aufklappen
296		# Meistbesuchte Seiten
297		# Koordinaten
298		# Breitengrad
299		# Längengrad
300		# Karte
301		# Doppelklicke auf einen Ort um die Koordinaten zu setzen
302		# Hilfe
303		# Manuelles Update
304		# Geschlecht
305		# Männlich
306		# Weiblich
307		# Nicht angegeben
308		# Persönliche Angaben
309		# Social Media
310		# Amerika
311		# Antarktis
312		# Arktis
313		# Asien
314		# Atlantik
315		# Europa
316		# Indien
317		# Pazifik
318		# Postleitzahl
319		# Ort
320		# Telefon
321		# Erlaubt
322		# Springe zu einem anderen Zweig
323		# Springe zu einem Element
324		# Neues Fenster
325		# Zweig
326		# Web-Feeds
327		# Erweiterungen
328		# Favicon
329		# Backups
330		# Kategorien
331		# Format
332		# Views	
333		# Empfohlen
334		# Beschreibung
335		# Einträge
336		# Anzeigen
337		# Zusammenfassung
338		# %d/%d Dateien hochgeladen
339		# Nicht verfügbar
340		# Dateierweiterungsfehler
341		# Dateigrößenfehler
342		# Inizialisierungsfehler
343		# HTTP-Fehler
344		# Sicherheitsfehler
345		# Allgemeiner Fehler
346		# Eingabe/Ausgabe-Fehler
347		# Upload stoppen
348		# Dateien hinzufügen
349		# Upload starten
350		# %d Dateien in der Warteschlange
351		# Neues Update verfügbar!
352		# Stimmen
353		# Ergebnis
354		# Zurücksetzen
355		# Zurückgesetzte Stimmen
356		# Die letzten 90 Tage
357		# Benutzerstimmen
358		# Für niemanden sichtbar
359		# Nur für Navigate CMS Benutzer sichtbar
360		# Für alle sichtbar
361		# Nur registrierte Benutzer
362		# Nicht registriert
363		# Benutzer, die sich noch nicht registriert oder angemeldet haben
364		# Zugang
365		# Installieren
366		# Log
367		# Themes
368		# Theme
369		# Mehr über
370		# Demo
371		# Beim Installation eines neuen Themes werden die Einstellungen des alten gelöscht.
372		# Die Liste der verfügbaren Block-Typen kann sich ändern und auch die Eigenschaften, die Elementen zugewiesen sind, können verloren gehen.
373		# Bist du sicher, dass du fortfahren willst?
374		# Element erfolgreich installiert.
375		# Blog
376		# Blog-Eintrag
377		# Kontakt
378		# Lizenz
379		# Schreibe einen Kommentar
380		# Nachricht
381		# Die E-Mail-Adresse wird nicht veröffentlicht
382		# Abschicken
383		# Registriere dich oder melde dich an um einen Kommentar zu verfassen
384		# Das Kommentieren ist für diesen Eintrag deaktiviert
385		# Bitte lasse keines der Felder leer
386		# Dein Kommentar ist eingegangen und wird in Kürze veröffentlicht
387		# Neue Kommentare
388		# Kommentare bearbeiten
389		# Backspace-Taste gesichert
390		# Test
391		# Versuche die E-Mail zu versenden ...
392		# E-Mail versendet
393		# Standard Banner-Größen
394     # Fixiert
395     # "Fixiert" weist eine feste Position zu, wenn die Anordnung zufällig ist
396		# Alle Kategorien
397		# Maximum
398		# Minimum
399		# Zufällig
400		# Gib 0 ein um alle anzuzeigen
401		# Dein Browser unterstützt kein HTML5
402		# Bitte wähle weniger Dateien aus
403		# Datei zu groß
404     # Sortieren nach
405     # Auswahl
406     # Erinnere dich an mich
407     # Passwort vergessen
408     # Die Reihenfolge wird nur auf Listen angewandt, die nach Priorität sortiert sind
409     # Größe
410     # Backup starten
411     # Fortschritt der Aufgabe
412     # Wiederherstellen
413     # Warte auf Beginn
414     # Datenbank wird exportiert
415     # Themes und Templates werden kopiert
416     # Extensions werden kopiert
417     # Uploads werden kopiert
418     # Das Archiv wird erstellt
419     # Der Vorgang ist abgeschlossen
420     # Geschätzte Größe
421		# Erstellt am
422     # Lädt auf den Server hoch
423     # Neu laden
424     # Vorgang wird vorbereitet
425     # Sortiere die Elemente einer Kategorie (es sei denn das Template gibt eine bestimmte Reihenfolge vor)
426     # Gib "1" für wahr ein und "0" für falsch
427     # TLS/SSL benötigt
428     # (keine Kategorie)
429     # Statistiken zurücksetzen
430     # Möchtest du wirklich alle Statistiken dieser Website löschen?
431     # Stil
432     # Read-Only-Modus
433		# Größe der hochgeladenen Bilder ändern
434		# Original-Datei übernehmen
435		# Maximale Breite oder Höhe
436     # Als Klasse in HTML-Elementen verwendet
437     # Block
438     # Reihenfolge
439     # Fehler beim Laden des Themes
440     # Fehler beim Speichern der Daten, bitte führe ein externes Backup deiner Daten durch um Datenverlust zu vermeiden.
441     # Farbe
442     # Hexadezimaler Farbcode
443     # Alle
444     # Du hast einige notwendige Felder leer gelassen.
445     # Deine Kontaktanfrage wurde abgeschickt. Wir werden uns in Kürze mit dir in Verbindung setzen.
446     # Es tut uns leid, aber deine Kontaktanfrage konnte nicht abgeschickt werden. Bitte versuche es noch einmal oder finde einen anderen Weg um mit uns Kontakt aufzunehmen
447     # Portfolio
448     # Portfolio-Element
449     # Gib deinen Navigate CMS Benutzernamen oder deine E-Mail-Adresse ein
450     # Klicke auf den Link unten um dein Passwort zu ändern
451     # Dies ist eine automatische E-Mail, die im Zuge einer Passwort-Anforderung versendet wurde. Wenn du diese Nachricht irrtümlicherweise bekommen hast, ignoriere sie einfach.
452     # Die E-Mail konnte nicht versendet werden; Bitte kontaktiere den Administrator
453     # Der Benutzername oder die E-Mail-Adresse wurde nicht gefunden
454     # Eine E-Mail mit einem Bestätigungscode wurde an deine E-Mail-Adresse geschickt.
455     # Dein neues Passwort ist nun aktiv
456     # In Navigate CMS bearbeiten
457     # Information
458     # Auf der Seite bearbeiten
459     # Einstellungen
460     # Deaktivieren
461     # Von einer Datei installieren
462     # Aktivieren
463     # Update verfügbar
464     # Favorit
465     # Favoriten
466     # Spam
467     # Geltungsbereich
468     # Integer
469     # String
470     # System
471     # Variante
472     # Hinzufügen
473     # Region
474     # Server locale
475     # Exportieren
476     # In die Zwischenablage kopieren
477     # Duplizieren
478     # Element erfolgreich dupliziert.
479     # Struktureintrag
480     # Exportiere Beispiel-Inhalt
481     # Alle auswählen
482     # Alle Beispiel-Dateien sollten sich in einem Ordner befinden. Navigate CMS wird Dateien hinzufügen, die für den Inhalt verwendet werden.
483     # Willst du für das ausgewählte Theme wirklich die Default-Website importieren?
484     # Demo-Website
485     # Aliase
486     # Alias
487     # Echte URL
488     # Textfeld mit Formatierungsmöglichkeiten
489     # Quellcode
490     # ID der Datei oder öffentliche URL des Videos
491     # Klasse
492     # Keine Übereinstimmungen gefunden
493     # Lade weitere Ergebnisse...
494     # Suche...
495     # Bitte gib mindestens {number} Zeichen ein
496     # Du kannst nur {number} Elemente auswählen
497     # Willst du diese Daten wirklich löschen?
498     # Zusätzliche Script
499     # Öffnen
500     # Umbenennen
501     # Vorheriges
502     # Nächstes
503     # Jetzt
504     # Zeit
505     # Weiterleiten nach
506     # Gruppen
507     # Auswahl für alle aufheben
508     # Zuklappen
509     # Aufklappen
510     # Ausgewählte Elemente
511     # Verfügbare Elemente
512     # Ausgewählte Web-Usergroups
513     # Metatags
514     # Zusätzlicher Header
515     # Wenn der Pfad nicht gefunden wird
516     # Eine leere Seite zeigen
517     # Zur Homepage weiterleiten
518     # 404-Template dieses Themes anzeigen (wenn es existiert)
519     # 404 HTTP Fehler-Header senden
520     # Keine Website gefunden; eine Default-Seite wurde erstellt.
521     # Extra
522     # Spam löschen
523     # Diese Aktion kann NICHT rückgängig gemacht werden.
524     # Elemente erfolgreich gelöscht
525     # Lösche Kommentar (ohne Bestätigung)
526     # Übersetzungen
527     # Marktplatz
528     # Verfügbar
529     # Es war nicht möglich, die Artikel aus dem Markt herunterladen.
530     # Sie müssen Ihre Marketplace Armaturenbrett besuchen und laden Sie die Datei, dann verwenden Sie die <strong> Install from file </ strong> Sie in der Aktionsleiste auf der rechten Seite zu finden.
531     # Sorry für die Unannehmlichkeiten.
532     # Navigate CMS Marketplace
533     # Finden Element nach Titel
534     # Sie können nur Elemente, die ihren eigenen Weg haben (keine Kategorie eingebettete Elemente)
535     # Finden Sie den Benutzernamen
536     # Stichworte
537     # Kann das Theme nicht zu entfernen, da sie derzeit von einer anderen Website verwendet.
538     # Privat Kommentar
539     # Dokument
540     # Mittelpunkt
541     # Ihre E-Mail wurde erfolgreich mit dem Newsletter.
542     # Es gab ein Problem Ihre E-Mail abonnieren Sie den Newsletter.
543     # Blocktyp
544     # Blockgruppen
545     # Inhalt Autor
546     # Aktionen
547     # Multi-Language
548     # Verfahren
549     # Links
550     # Quickinfo
551     # Datum angezeigt
552     # Ausschlüsse
553     # Fragmente
554     # Verbergen
555     # Der Artikel wurde veröffentlicht.
556     # Block Gruppe
557     # Umfrage
558     # Frage
559     # Antworten
560     # Wählen
561     # Erstellen Sie einen Ordner
562     # Ergebnisse
563     # Letzter Besuch