0 		# Navigate
1 		# User
2 		# Password
3		# Enter
4		# Login incorrect.
5		# Log out
6		# Loading
7		# Configuration
8		# Web
9		# Content
10		# Shop
11		# Multimedia
12		# Tools
13		# /*/
14		# Preferences
15		# Users
16		# Structure
17		# Permissions
18		# Home
19		# Structure
20		# Templates
21		# Dictionary
22		# Elements
23		# Blocks
24		# Web users
25		# Products
26		# Orders
27		# Rates
28		# Shipping
29		# Images
30		# Videos
31		# Audio
32		# Documents
33		# Newsletters
34		# Save
35		# Delete
36		# Media
37		# /*/
38		# Create
39		# List
40		# History
41		# Search
42		# Ready
43		# Main
44		# E-Mail
45		# Profile
46		# Language
47		# Blocked
48		# Leave empty to keep current value
49		# Decimal separator
50		# Date format
51		# List
52		# (new)
53		# Data successfully saved
54		# Text
55		# Item successfully deleted
56		# Unexpected error
57		# Do you really want to delete the item?
58		# Cancel
59		# Confirmation
60		# Do you really want to delete the selected items?
61		# Tree
62		# Statistics
63		# Languages
64		# Published
65		# Enabled
66		# Priority
67		# Title
68		# Status
69		# Published
70		# Private
71		# Closed
72		# Drag the rows to assign priorities
73		# Children
74		# Paths
75		# Path
76		# Visible
77		# Properties
78		# Category
79		# Template
80		# Permission
81		# Hidden
82		# File
83		# Leave blank to disable
84		# Parent
85		# Publish date
86		# Date
87		# Association
88		# Galleries
89		# Files
90		# Unpublish date
91		# Day of month
92		# Close
93		# Hour
94		# Minute
95		# Month
96		# Second
97		# Timezone
98		# Select a date
99		# Year
100		# Free
101		# January
102		# February
103		# March
104		# April
105		# May
106		# June
107		# July
108		# August
109		# September
110		# October
111		# November
112		# December
113		# Jan
114		# Feb
115		# Mar
116		# Apr
117		# May
118		# Jun
119		# Jul
120		# Aug
121		# Sep
122		# Oct
123		# Nov
124		# Dec
125		# Monday
126		# Tuesday
127		# Wednesday
128		# Thursday
129		# Friday
130		# Saturday
131		# Sunday
132		# Mon
133		# Tue
134		# Wed
135		# Thu
136		# Fri
137		# Sat
138		# Sun
139		# Back
140		# Load
141		# Folder
142		# Select files
143		# Add files to upload queue and push the button to start the process
144		# Filename
145		# Size
146		# Select files
147		# Start upload
148		# Stop current upload
149		# Start upload queue
150		# Drag and drop files here
151		# The selected items will be permanently deleted.
152		# Continue
153		# Embedding link
154		# Download link
155		# Width
156		# Height
157		# Image
158		# Thumbnail
159		# Name
160		# Type
161		# Generic
162		# Embedding
163		# Embedded
164		# Own path
165		# The full content is shown in category view. Ex. "Who we are"
166		# Content is accessed via its own path. Ex. "News"
167		# Types
168		# Notes
169		# You can leave a field blank to keep the size free
170		# Edit
171		# Order
172		# Action
173		# Follow URL
174		# Open URL (new window)
175		# Download file
176		# Watch image
177		# Website
178		# Services
179		# Thumbnails
180		# Item
181		# Hidden
182		# Rollover image
183		# Do nothing
184		# Web page
185		# Searching items
186		# Adobe Flash
187		# Home page
188		# Translate
189		# Copy from
190		# Ok
191		# Source
192		# Double click a row to edit it
193		# Value
194		# Option
195		# Text area
196		# Date and time
197		# Link
198		# Product
199		# Default value
200		# Options
201		# One line per option, following the format: value#title
202		# Enter only the value
203		# Same value for all languages
204		# File ID
205		# Comment
206		# Boolean
207		# Default timezone
208		# /*/
209		# Minutes
210		# Gallery
211		# Multiple option
212		# Write values separated by commas
213		# Image caption
214		# Product
215		# Credits
216		# Created by
217		# Tested by
218		# External libraries
219		# Copyright
220		# Version
221		# Jump to
222		# Rating
223		# Default value 5 stars, if you want a different value: default_value#number_of_stars
224		# Country
225		# Alpha-2 country code
226		# Creation date
227		# Modification date
228		# Subdomain
229		# Domain
230		# Ex.
231		# Server
232		# Port
233		# Address
234		# More elements
235		# File saved successfully.
236		# Sections
237		# Code
238		# Main content
239		# Section
240		# Functions
241		# Web sites
242		# Icon
243		# Profiles
244		# Menus
245		# Notes
246		# Avatar
247		# Registration date
248		# Birth date
249		# Newsletter
250		# Comments
251		# Private
252		# Comments enabled for
253		# Nobody
254		# Everybody
255		# Moderator
256		# Leave blank to accept all comments
257		# To revise
258		# Publish
259		# Unpublish
260		# Drag and drop files to upload them
261		# Uploading
262		# Error uploading file
263		# Contact e-mails
264		# One item per row
265		# Labels
266		# Author
267		# Editor
268		# Raw
269		# HTML code
270		# Auto save in progress
271		# Auto save completed
272		# Video
273		# Auto save
274		# Preview
275		# Recent elements
276		# Recent comments
277		# Most seen elements
278		# Web summary
279		# pages available
280		# page views
281		# comments to revise
282		# Untitled
283		# Show in menus
284		# /*/
285		# Update
286		# Drag to reorder. Double click to assign image captions.
287		# Protocol
288		# Secure site (requires certificate)
289		# Update Navigate
290		# Current version
291		# Last version
292		# Available updates
293		# Application successfully updated
294		# Error updating.
295		# Expand all
296		# Top pages
297		# Coordinates
298		# Latitude
299		# Longitude
300		# Map
301		# Double click a place to set the coordinates
302		# Help
303		# Manual update
304		# Gender
305		# Male
306		# Female
307		# Unspecified
308		# Personal
309		# Social
310		# America
311		# Antartica
312		# Arctic
313		# Asia
314		# Atlantic
315		# Europe
316		# Indian
317		# Pacific
318		# Zip code
319		# Location
320		# Phone
321		# Allowed
322		# Jump to another branch
323		# Jump to an element
324		# New window
325		# Branch
326		# Web feeds
327		# Extensions
328		# Favicon
329		# Backups
330		# Categories
331		# Format
332		# Views
333		# Recommended
334		# Description
335		# Entries
336		# Display
337		# Summary
338		# Uploaded %d/%d files
339		# N/A
340		# File extension error
341		# File size error
342		# Init error
343		# HTTP Error
344		# Security error
345		# Generic error
346		# IO error
347		# Stop upload
348		# Add files
349		# Start upload
350		# %d files queued
351		# New update available!
352		# Votes
353		# Score
354		# Reset
355		# Votes reset
356		# last 90 days
357		# User votes
358		# Hidden to everybody
359		# Visible only to Navigate CMS users
360		# Visible to everybody
361		# Web users only
362		# Not signed in
363		# Users who have not yet signed up or signed in
364		# Access
365		# Install
366		# Log
367		# Themes
368		# Theme
369		# More on
370		# Demo
371		# Installing a new theme removes the settings of the old one.
372		# The list of available block types may change and also the properties assigned to items could be lost.
373		# Are you sure you want to continue?
374		# Item installed successfully.
375		# Blog
376		# Blog entry
377		# Contact
378		# License
379		# Post a comment
380		# Message
381		# E-Mail will not be published
382		# Submit
383		# Sign in or Sign up to post a comment
384		# Comments on this entry are closed
385		# Please don't leave any field blank
386		# Your comment has been received and will be published shortly
387		# New comment
388		# Review comments
389		# Backspace key protection
390		# Test
391		# Trying to send a test e-mail...
392		# E-Mail sent
393		# Standard banner sizes
394     # Fixed
395     # "Fixed" assigns a static position when the order is random
396		# All categories
397		# Maximum
398		# Minimum
399		# Random
400		# Enter 0 to display all
401		# Your browser does not support HTML5
402		# Please select fewer files
403		# File too large
404     # Order by
405     # Selection
406     # Remember me
407     # Forgot password?
408     # Order is only used on lists ordered by priority
409     # Size
410     # Begin backup
411     # Task progress
412     # Restore
413     # Waiting to begin
414     # Exporting database
415     # Copying themes and templates
416     # Copying extensions
417     # Copying uploads
418     # Creating archive
419     # Process complete
420     # Estimated size
421		# Created on
422     # Uploading to server
423     # Refresh
424     # Preparing process
425     # Order the elements of a category (unless the template forces other sorting)
426     # Enter "1" for true, "0" for false
427     # TLS/SSL required
428     # (no category)
429     # Reset statistics
430     # Do you really want to remove all statistics of this website?
431     # Style
432     # Read only mode
433		# Resize uploaded images
434		# Keep original file
435		# Maximum width or height
436     # Used as a class in HTML elements
437     # Block
438     # Order
439     # Error loading theme
440     # Error saving the data, please do an external backup of your changes to prevent data loss
441     # Color
442     # Hexadecimal color code
443     # All
444     # You left some required fields blank.
445     # Your contact request has been sent. We will contact you shortly.
446     # We're sorry. Your contact request could not be sent. Please try again or find another way to contact us.
447     # Portfolio
448     # Portfolio item
449     # Enter your Navigate CMS username or e-mail address
450     # Click on the link below to change your password
451     # This is an automated e-mail sent as a result of a password request process. If you received this e-mail by error just ignore it.
452     # E-mail could not be sent; please contact the administrator
453     # Couldn't find this username or e-mail address
454     # An e-mail with a confirmation link has been sent to your e-mail account.
455     # Your new password has been activated.
456     # Edit in Navigate CMS
457     # Information
458     # Edit in place
459     # Settings
460     # Disable
461     # Install from file
462     # Enable
463     # Update available
464     # Favorite
465     # Favorites
466     # Spam
467     # Scope
468     # Integer
469     # String
470     # System
471     # Variant
472     # Add
473     # Region
474     # Server locale
475     # Export
476     # Copy to clipboard
477     # Duplicate
478     # Item duplicated successfully.
479     # Structure entry
480     # Export sample content
481     # Select all
482     # All sample files should be placed in a folder. Navigate CMS will also add files used in contents.
483     # Do you really want to import the default website for the selected theme?
484     # Demo website
485     # Aliases
486     # Alias
487     # Real URL
488     # Rich textarea
489     # Source code
490     # ID of the file or public video URL
491     # Class
492     # No matches found
493     # Loading more results...
494     # Searching...
495     # Please enter at least {number} characters
496     # You can only select {number} items
497     # Do you really want to erase this data?
498     # Statistics script
499     # Open
500     # Rename
501     # Previous
502     # Next
503     # Now
504     # Time
505     # Redirect to
506     # Groups
507     # Deselect all
508     # Collapse
509     # Expand
510     # Selected items
511     # Available items
512     # Selected web user groups
513     # Metatags
514     # Additional headers
515     # Not found paths
516     # Show a blank page
517     # Redirect to home page
518     # Use the 404 template of a theme (if exists)
519     # Send a 404 HTTP error header
520     # No website found; a default one has been created.
521     # Extra
522     # Remove Spam
523     # This action can NOT be undone.
524     # Items removed successfully
525     # Remove comment (without confirmation)
526     # Translations