0 		# Navigate
1 		# Usuario
2 		# Contraseña
3		# Entrar
4		# Datos de identificación incorrectos.
5		# Cerrar sesión
6		# Cargando
7		# Configuración
8		# Web
9		# Contenido
10		# Tienda
11		# Multimedia
12		# Herramientas
13		# phpMyAdmin
14		# Preferencias
15		# Usuarios
16		# Estructura
17		# Permisos
18		# Inicio
19		# Estructura
20		# Plantillas
21		# Diccionario
22		# Elementos
23		# Bloques
24		# Usuarios web
25		# Productos
26		# Pedidos
27		# Tarifas
28		# Portes
29		# Imágenes
30		# Vídeos
31		# Audio
32		# Documentos
33		# Boletines
34		# Guardar
35		# Eliminar
36		# Media
37		# NaviM+
38		# Crear
39		# Listar
40		# Historial
41		# Buscar
42		# Preparado
43		# Principal
44		# E-Mail
45		# Perfil
46		# Idioma
47		# Bloqueado
48		# Dejar vacía para mantener el valor actual
49		# Separador decimal
50		# Formato de fecha
51		# Lista
52		# (nuevo)
53		# Datos guardados correctamente
54		# Texto
55		# Elemento eliminado correctamente
56		# Error inesperado
57		# ¿Realmente desea eliminar el elemento?
58		# Cancelar
59		# Confirmación
60		# ¿Realmente desea eliminar los elementos seleccionados?
61		# Árbol
62		# Estadísticas
63		# Idiomas
64		# Publicado
65		# Activado
66		# Prioridad
67		# Título
68		# Estado
69		# Publicada
70		# Privada
71		# Cerrada
72		# Arrastre las filas para determinar la prioridad
73		# Hijos
74		# Rutas
75		# Ruta
76		# Visible
77		# Propiedades
78		# Categoría
79		# Plantilla
80		# Permiso
81		# Oculta
82		# Fichero
83		# Dejar en blanco para deshabilitar
84		# Padre
85		# Fecha de publicación
86		# Fecha
87		# Asociación
88		# Galerías
89		# Ficheros
90		# Fecha de despublicación
91		# Día del mes
92		# Cerrar
93		# Hora
94		# Minuto
95		# Mes
96		# Segundo
97		# Zona horaria
98		# Seleccione una fecha
99		# Año
100		# Libre
101		# Enero
102		# Febrero
103		# Marzo
104		# Abril
105		# Mayo
106		# Junio
107		# Julio
108		# Agosto
109		# Septiembre
110		# Octubre
111		# Noviembre
112		# Diciembre
113		# Ene
114		# Feb
115		# Mar
116		# Abr
117		# May
118		# Jun
119		# Jul
120		# Ago
121		# Sep
122		# Oct
123		# Nov
124		# Dic
125		# Lunes
126		# Martes
127		# Miércoles
128		# Jueves
129		# Viernes
130		# Sábado
131		# Domingo
132		# Lun
133		# Mar
134		# Mié
135		# Jue
136		# Vie
137		# Sáb
138		# Dom
139		# Atrás
140		# Cargar
141		# Carpeta
142		# Elegir ficheros
143		# Añada ficheros a la cola de subida y pulse el botón para iniciar la carga
144		# Nombre del fichero
145		# Tamaño
146		# Seleccionar ficheros
147		# Iniciar carga
148		# Detener carga actual
149		# Iniciar cola de carga
150		# Arrastre ficheros aquí
151		# Los elementos seleccionados serán borrados y no podrán ser recuperados.
152		# Continuar
153		# Enlace de integración
154		# Enlace de descarga
155		# Ancho
156		# Alto
157		# Imagen
158		# Miniatura
159		# Nombre
160		# Tipo
161		# Genérico
162		# Incrustación
163		# Incrustado
164		# Ruta propia
165		# El contenido completo se muestra en la vista de categoría. Ej. "¿Quiénes somos?"
166		# Se accede al contenido a través de una ruta independiente. Ej. "Noticias"
167		# Tipos
168		# Notas
169		# Puede dejar en blanco un campo para no limitar el tamaño
170		# Editar
171		# Ordenar
172		# Acción
173		# Seguir URL
174		# Abrir URL (nueva ventana)
175		# Descargar fichero
176		# Ver imagen
177		# Sitio web
178		# Servicios
179		# Miniaturas
180		# Elemento
181		# Oculto
182		# Imagen activa
183		# No hacer nada
184		# Página web
185		# Buscando elementos
186		# Adobe Flash
187		# Página inicial
188		# Traducir
189		# Copiar de
190		# Aceptar
191		# Origen
192		# Haga doble click sobre una fila para editarla
193		# Valor
194		# Opción
195		# Área de texto
196		# Fecha y hora
197		# Enlace
198		# Artículo
199		# Valor por defecto
200		# Opciones
201		# Una línea para cada opción, siguiendo el formato: valor#título
202		# Escriba sólo el valor
203		# El mismo valor para todos los idiomas
204		# ID del fichero
205		# Comentario
206		# Booleano
207		# Zona horaria por defecto
208		# Fecha actual incluyendo el ajuste
209		# Minutos
210		# Galería
211		# Opción múltiple
212		# Escriba los valores seleccionados separados por comas
213		# Texto de la imagen
214		# Producto
215		# Créditos
216		# Creado por
217		# Testeado por
218		# Librerías externas
219		# Copyright
220		# Versión
221		# Saltar a
222		# Valoración
223		# Por defecto 5 estrellas, si quiere un número distinto: valor_defecto#número_de_estrellas
224		# País
225		# Código alpha-2 del país
226		# Fecha de creación
227		# Fecha de modificación
228		# Subdominio
229		# Dominio
230		# Ej.
231		# Servidor
232		# Puerto
233		# Dirección
234		# Más elementos
235		# Fichero guardado correctamente.
236		# Secciones
237		# Código
238		# Contenido principal
239		# Sección
240		# Funciones
241		# Sitios web
242		# Icono
243		# Perfiles
244		# Menús
245		# Notas
246		# Avatar
247		# Fecha de registro
248		# Fecha de nacimiento
249		# Boletín electrónico
250		# Comentarios
251		# Privado
252		# Comentarios activos para
253		# Nadie
254		# Todo el mundo
255		# Moderador
256		# Dejar en blanco para aceptar todos los comentarios
257		# Por revisar
258		# Publicar
259		# Despublicar
260		# Arrastre y suelte archivos para cargarlos
261		# Subiendo
262		# Error cargando fichero
263		# E-Mails de contacto
264		# Una entrada por línea
265		# Etiquetas
266		# Autor/a
267		# Editor
268		# Sin formato
269		# Código HTML
270		# Guardando automáticamente
271		# Guardado automático completado
272		# Vídeo
273		# Autoguardado
274		# Previsualizar
275		# Elementos recientes
276		# Comentarios recientes
277		# Elementos más vistos
278		# Resumen de la web
279		# Páginas disponibles
280		# Páginas vistas
281		# Comentarios por revisar
282		# Sin título
283		# Se muestra en los menús
284		# África
285		# Actualizar
286		# Arrastre para reordenar. Haga doble clic para asignar títulos a la imagen.
287		# Protocolo
288		# Sitio seguro (requiere certificado)
289		# Actualizar Navigate
290		# Versión actual
291		# Última versión
292		# Actualizaciones disponibles
293		# Actualizado correctamente.
294		# Error actualizando.
295		# Expandir todo
296		# Páginas más vistas
297		# Coordenadas
298		# Latitud
299		# Longitud
300		# Mapa
301		# Haga doble clic en un sitio para establecer las coordenadas
302		# Ayuda
303		# Actualización manual
304		# Sexo
305		# Masculino
306		# Femenino
307		# No especificado
308		# Personal
309		# Social
310		# América
311		# Antártida
312		# Ártico
313		# Asia
314		# Atlántico
315		# Europa
316		# Índico
317		# Pacífico
318		# Código postal
319		# Localidad
320		# Teléfono
321		# Permitido
322		# Saltar a otra rama
323		# Saltar a un elemento
324		# Nueva ventana
325		# Rama
326		# Fuentes web
327		# Extensiones
328		# Favicon
329		# Copias de seguridad
330		# Categorías
331		# Formato
332		# Vistas
333		# Recomendado
334		# Descripción
335		# Entradas
336		# Mostrar
337		# Resumen
338		# Subidos %d/%d archivos
339		# No disponible
340		# Error en extensión del fichero
341		# Error en tamaño de fichero
342		# Error de inicialización
343		# Error HTTP
344		# Error de seguridad
345		# Error genérico
346		# Error de entrada/salida
347		# Detener subida
348		# Añadir ficheros
349		# Iniciar subida
350		# %d ficheros en cola
351		# ¡Nueva actualización disponible!
352		# Votos
353		# Nota
354		# Reiniciar
355		# Votos reiniciados
356		# últimos 90 días
357		# Votos de usuarios
358		# No se muestra a nadie
359		# Sólo visible a usuarios de Navigate CMS
360		# Se muestra a todos
361		# Sólo usuarios registrados
362		# No registrados
363		# Usuarios que aún no se han registrado o identificado
364		# Acceso
365		# Instalar
366		# Registro
367		# Temas
368		# Tema
369		# Más en
370		# Demo
371		# Instalar un nuevo tema elimina la configuración del anterior.
372		# La lista de tipos de bloques disponibles puede perderse así como las propiedades asignadas a elementos.
373		# Realmente desea continuar?
374		# Elemento instalado correctamente.
375		# Blog
376		# Entrada de blog
377		# Contacto
378		# Licencia
379		# Escribir un comentario
380		# Mensaje
381		# El correo electrónico no será mostrado
382		# Enviar
383		# Indentifíquese o Regístrese para escribir un comentario
384		# Los comentarios para esta entrada están cerrados
385		# Por favor no deje ningún campo en blanco
386		# Su comentario ha sido recibido y será publicado en breve
387		# Nuevo comentario
388		# Revisar comentarios
389		# Protección de tecla Retroceso
390		# Probar
391		# Intentando enviar un correo de prueba...
392		# Mensaje enviado
393		# Tamaños publicitarios estándar
394     # Fijo
395     # "Fijo" determina una posición estática cuando el orden es aleatorio
396		# Todas las categorías
397		# Máximo
398		# Mínimo
399		# Aleatorio
400		# Escriba 0 para mostrarlos todos
401		# Su navegador no integra HTML5
402		# Por favor, seleccione un número menor de ficheros
403		# Fichero demasiado grande
404     # Ordenar por
405     # Selección
406     # Recordarme
407     # ¿Olvidaste la contraseña?
408     # El orden sólo se usa en listas ordenadas por prioridad
409     # Tamaño
410     # Iniciar copia de seguridad
411     # Progreso de la tarea
412     # Restaurar
413     # Esperando para empezar
414     # Exportando base de datos
415     # Copiando temas y plantillas
416     # Copiando extensiones
417     # Copiando ficheros subidos
418     # Creando archivo comprimido
419     # Proceso completado
420     # Tamaño estimado
421		# Fecha de creación
422     # Transfiriendo al servidor
423     # Comprobar
424     # Preparando proceso
425     # Ordenar los elementos de una categoría (excepto cuando la plantilla fuerza otra ordenación)
426     # Introduzca "1" para verdadero, "0" para falso
427     # TLS/SSL requerido
428     # (sin categoría)
429     # Reiniciar estadísticas
430     # ¿Realmente desea borrar todas las estadísticas de este sitio web?
431     # Estilo
432     # Modo de sólo lectura
433		# Tamaño imágenes cargadas
434		# Conservar fichero original
435		# Ancho o alto máximo
436     # Usado como una clase en elementos HTML
437     # Bloque
438     # Ordenación
439     # Error cargando el tema
440     # Error guardando los datos, por favor haga una copia externa de los cambios que ha realizado para evitar pérdidas de datos
441     # Color
442     # Código de color hexadecimal
443     # Todos
444     # Ha dejado algunos campos requeridos en blanco.
445     # Su solicitud de contacto ha sido enviada. Pronto nos pondremos en contacto con usted.
446     # Lo sentimos. Su solicitud de contacto no pudo ser entregada. Por favor, inténtelo de nuevo o elija otra vía para contactar con nosotros.
447     # Colección
448     # Elemento de colección
449     # Introduce tu nombre de usuario de Navigate CMS o tu dirección de correo electrónico
450     # Haz clic en el enlace inferior para cambiar tu contraseña
451     # Este es un correo automático enviado como resultado de un proceso de petición de cambio de contraseña. Si has recibido este correo por error simplemente ignóralo.
452     # No se pudo enviar el correo electrónico; por favor contacta con el administrador
453     # No se ha encontrado este nombre de usuario o cuenta de correo
454     # Se ha enviado un correo electrónico a tu cuenta con un enlace de confirmación.
455     # Tu nueva contraseña ha sido activada.
456     # Editar en Navigate CMS
457     # Información
458     # Editar en la página
459     # Ajustes
460     # Desactivar
461     # Instalar desde fichero
462     # Activar
463     # Actualización disponible
464     # Favorito
465     # Favoritos
466     # No deseado (Spam)
467     # Ámbito
468     # Entero
469     # Cadena
470     # Sistema
471     # Variante
472     # Añadir
473     # Región
474     # Locale en el servidor
475     # Exportar
476     # Copiar al portapapeles
477     # Duplicar
478     # Ítem duplicado correctamente.
479     # Entrada en estructura
480     # Exportar contenido de ejemplo
481     # Seleccionar todo
482     # Todos los ficheros de ejemplo deberán estar en una carpeta. Navigate CMS añadirá todos los ficheros usados en contenidos.
483     # ¿Realmente desea importar el sitio web por defecto del tema seleccionado?
484     # Web demo
485     # Alternativas
486     # Alias
487     # Dirección real
488     # Área de texto con estilos
489     # Código fuente
490     # ID del fichero o URL pública del vídeo
491     # Clase
492     # No se encontraron resultados
493     # Cargando más datos...
494     # Buscando...
495     # Por favor introduzca un mínimo de {number} caracteres
496     # Sólo puede seleccionar {number} elementos
497     # ¿Realmente desea eliminar los datos?
498     # Scripts adicionales
499     # Abrir
500     # Renombrar
501     # Anterior
502     # Siguiente
503     # Ahora
504     # Hora
505     # Redirigir a
506     # Grupos
507     # Deseleccionar todo
508     # Plegar
509     # Desplegar
510     # Elementos seleccionados
511     # Elementos disponibles
512     # Selección de grupos de usuarios web
513     # Metatags
514     # Cabeceras adicionales
515     # Las rutas no encontradas
516     # Muestran una página en blanco
517     # Redirigen a la página de inicio
518     # Usan la plantilla 404 de un tema (si existe)
519     # Envían una cabecera de error HTTP 404
520     # Ningún sitio web encontrado; se ha creado uno por defecto.
521     # Extra
522     # Borrar Spam
523     # Esta operación no podrá deshacerse.
524     # Elementos eliminados correctamente
525     # Borrar comentario (sin confirmación)
526     # Traducciones
527     # Mercado
528     # Disponibles
529     # No ha sido posible descargar el objeto desde la tienda.
530     # Tendrás que visitar tu zona privada en la tienda para descargar el fichero, luego usar el botón <strong>Instalar desde fichero</strong> que encontrarás en la barra de acciones de la derecha.
531     # Disculpa las molestias.
532     # Tienda de Navigate CMS
533     # Encontrar elemento por título
534     # Sólo puedes seleccionar elementos que tengan su propia ruta (no elementos incrustados a una categoría)
535     # Encontrar usuario por nombre
536     # Palabras clave
537     # No se puede eliminar el tema porque actualmente está siendo usado por otro sitio web.
538     # Comentario privado
539     # Documento
540     # Punto focal
541     # Tu correo electrónico ha sido correctamente suscrito al boletín.
542     # Ha ocurrido un problema suscribiendo tu correo electrónico al boletín.
543     # Tipo de bloque
544     # Grupos de bloques
545     # Autor del contenido
546     # Acciones
547     # Multi-idioma
548     # Método
549     # Enlaces
550     # Texto de ayuda
551     # Fecha a mostrar
552     # Exclusiones
553     # Fragmentos
554     # Esconder
555     # El elemento ha sido publicado correctamente.
556     # Bloque del grupo
557     # Encuesta
558     # Pregunta
559     # Respuestas
560     # Votar
561     # Crear una carpeta
562     # Resultados
563     # Última visita
564     # hace %s segundos
565     # hace un minuto
566     # hace %m minutos
567     # hace una hora
568     # hace %h horas
569     # ayer
570     # hace %d días
571     # hace una semana
572     # hace %w semanas
573     # hace un mes
574     # hace %m meses
575     # hace un año
576     # hace %y años
577     # Últimas modificaciones
578     # No se ha podido conectar para comprobar las actualizaciones
579     # Últimas búsquedas
580     # Se usa en esta página
581     # Ninguno
582     # por defecto
583     # Mismo ancho
584     # Mismo alto
585     # Mismo tamaño (escalado)
586     # Mismo tamaño (recortado)
587     # Todo el espacio disponible
588     # Reemplazar imagen
589     # América del norte
590     # América del sur
591     # Oceanía
592     # Empresa
593     # Añadir hijo
594     # Definir como página de inicio
595     # Ahora mismo la página de inicio está definida como un elemento de la estructura que permite la redirección multi-idioma.
596     # ¿Quieres introducir una ruta fija para la página de inicio?
597     # Compartir ficheros en ventana Multimedia
598     # Sólo entre sitios web de esta instalación de Navigate CMS
599     # No es posible mostrar la información de un tipo de bloque de un tema.
600     # Compartir
601     # Importar
602     # Editar idioma
603     # Reemplazar URLs
604     # Anterior
605     # Nueva
606     # No se permiten comillas dobles, sólo pueden usarse comillas simples